/** @type {import('tailwindcss').Config} */


module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    colors: {
      'sp-color-background-subtle': 'var(--al-color-neutral-50)',
      'sp-color-background-lightest': 'var(--al-color-black-0)',
      'sp-color-text-extreme': 'var(--al-color-black-900)',
      'sp-color-text-medium': 'var(--al-color-black-300)',
      'sp-color-text-lightest': 'var(--al-color-black-0)',
      'sp-color-text-subtle': 'var(--al-color-neutral-500)',
      'sp-color-text-strong': 'var(--al-color-neutral-800)',
      'sp-color-text-disable': 'var(--al-color-black-400)',
      'sp-color-text-disable-inverse': 'var(--al-color-black-500)',
      'sp-color-text-accent': 'var(--al-color-gold-600)',
      'sp-color-text-brand-extreme': 'var(--al-color-magenta-700)',
      'sp-color-text-brand-strong': 'var(--al-color-magenta-600)',
      'sp-color-text-brand-medium': 'var(--al-color-magenta-500)',
      'sp-color-text-feedback-success': 'var(--al-color-green-600)',
      'sp-color-text-feedback-warning': 'var(--al-color-orange-700)',
      'sp-color-text-feedback-critical': 'var(--al-color-red-600)',
      'sp-color-surface-feedback-success-strong': 'var(--al-color-green-500)',
      'sp-color-surface-feedback-success-subtle': 'var(--al-color-green-50)',
      'sp-color-surface-feedback-critical-strong': 'var(--al-color-red-500)',
      'sp-color-surface-feedback-critical-subtle': 'var(--al-color-red-50)',
      'sp-color-surface-feedback-warning-strong': 'var(--al-color-orange-500)',
      'sp-color-surface-feedback-warning-subtle': 'var(--al-color-orange-50)',
      'sp-color-surface-feedback-informative-strong': 'var(--al-color-blue-500)',
      'sp-color-surface-feedback-informative-subtle': 'var(--al-color-blue-50)',
      'sp-color-surface-brand-strong': 'var(--al-color-magenta-600)',
      'sp-color-surface-brand-medium': 'var(--al-color-magenta-500)',
      'sp-color-surface-brand-subtle': 'var(--al-color-magenta-50)',
      'sp-color-surface-accent-strong': 'var(--al-color-gold-600)',
      'sp-color-surface-opacity-subtle': 'rgba(255 255 255 / 0.25)',
      'sp-color-surface-opacity-hover': 'rgba(255 255 255 / 0.1)',
      'sp-color-border-feedback-success': 'var(--al-color-green-500)',
      'sp-color-border-feedback-critical': 'var(--al-color-red-500)',
      'sp-color-border-brand-strong': 'var(--al-color-magenta-700)',
      'sp-color-border-brand-medium': 'var(--al-color-magenta-500)',
      'sp-color-border-focus': 'var(--al-color-gold-500)',
      'sp-color-border-extreme': 'var(--al-color-neutral-800)',
      'sp-color-border-strong': 'var(--al-color-neutral-500)',
      'sp-color-border-disable': 'var(--al-color-neutral-300)',
      'sp-color-border-subtle': 'var(--al-color-black-100)',
      'sp-color-border-light': 'var(--al-color-neutral-50)',
      'sp-color-icon-darkest': 'var(--al-color-black-900)',
      'sp-color-icon-extreme': 'var(--al-color-black-800)',
      'sp-color-icon-strong': 'var(--al-color-neutral-800)',
      'sp-color-icon-disable': 'var(--al-color-black-400)',
      'sp-color-icon-medium': 'var(--al-color-black-300)',
      'sp-color-icon-lightest': 'var(--al-color-black-0)',
      'sp-color-icon-disable-inverse': 'var(--al-color-black-500)',
      'sp-color-icon-accent-strong': 'var(--al-color-gold-600)',
      'sp-color-icon-accent-medium': 'var(--al-color-gold-500)',
      'sp-color-icon-brand-strong': 'var(--al-color-magenta-600)',
      'sp-color-icon-brand-subtle': 'var(--al-color-magenta-100)',
      'sp-color-icon-feedback-success': 'var(--al-color-green-600)',
      'sp-color-icon-feedback-warning': 'var(--al-color-orange-700)',
      'sp-color-icon-feedback-critical': 'var(--al-color-red-600)',
      'sp-color-surface-subtle': 'var(--al-color-black-100)',
      'sp-color-icon-subtle': 'var(--al-color-neutral-500)',
      'sp-color-surface-lightest': 'var(--al-color-black-0)',
      'sp-color-surface-disable-inverse': 'var(--al-color-black-200)',
      'sp-color-surface-disable': 'var(--al-color-black-100)',
      'sp-color-surface-brand-extreme': 'var(--al-color-magenta-700)',
      'sp-color-icon-brand-extreme': 'var(--al-color-magenta-700)',
      'sp-color-surface-medium': 'var(--al-color-neutral-400)',
      'sp-color-background-dark': 'var(--al-color-black-800)',
    },
    spacing: {
      'space-sm': 'var(--al-space-sm)',
      'space-md': 'var(--al-space-md)',
      'space-lg': 'var(--al-space-lg)',
      'space-xl': 'var(--al-space-xl)',
      'space-2xl': 'var(--al-space-2xl)',
      'space-3xl': 'var(--al-space-3xl)',
      'space-4xl': 'var(--al-space-4xl)',
      'space-5xl': 'var(--al-space-5xl)',
      'space-6xl': 'var(--al-space-6xl)',
      'space-7xl': 'var(--al-space-7xl)',
      'space-8xl': 'var(--al-space-8xl)',
    },
    fontFamily: {
      'primary': 'var(--al-font-family-primary)',
      'secondary': 'var(--al-font-family-secondary)',
    },
    fontWeight: {
      'light': 'var(--al-font-weight-light)',
      'regular': 'var(--al-font-weight-regular)',
      'bold': 'var(--al-font-weight-bold)',
    },
    fontSize: {
      'size-sm': 'var(--al-font-size-sm)',
      'size-md': 'var(--al-font-size-md)',
      'size-lg': 'var(--al-font-size-lg)',
      'size-xl': 'var(--al-font-size-xl)',
      'size-2xl': 'var(--al-font-size-2xl)',
      'size-3xl': 'var(--al-font-size-3xl)',
      'size-4xl': 'var(--al-font-size-4xl)',
      'size-5xl': 'var(--al-font-size-5xl)',
      'size-6xl': 'var(--al-font-size-6xl)',
      'size-7xl': 'var(--al-font-size-7xl)',
      'size-8xl': 'var(--al-font-size-8xl)',
      'size-display': 'var(--al-font-size-display)',
      'size-giant': 'var(--al-font-size-giant)',
    },
    letterSpacing: {
      'letter-spacing-base': 'var(--al-font-letter-spacing-base)',
      'letter-spacing-short': 'var(--al-font-letter-spacing-short)',
      'letter-spacing-half': 'var(--al-font-letter-spacing-half)',
      'letter-spacing-long': 'var(--al-font-letter-spacing-long)',
    },
    lineHeight: {
      'line-height-base': 'var(--al-font-line-height-base)',
      'line-height-short': 'var(--al-font-line-height-short)',
      'line-height-half': 'var(--al-font-line-height-half)',
      'line-height-long': 'var(--al-font-line-height-long)',
    },
    extend: {
      borderRadius: {
        'radius-square': 'var(--al-border-radius-square)',
        'radius-sm': 'var(--al-border-radius-sm)',
        'radius-md': 'var(--al-border-radius-md)',
        'radius-lg': 'var(--al-border-radius-lg)',
        'radius-xl': 'var(--al-border-radius-xl)',
        'radius-2xl': 'var(--al-border-radius-2xl)',
        'radius-pill': 'var(--al-border-radius-pill)',
        'radius-circle': 'var(--al-border-radius-circle)',
      },
      borderWidth: {
        'width-none': 'var(--al-border-width-none)',
        'width-thin': 'var(--al-border-width-thin)',
        'width-regular': 'var(--al-border-width-regular)',
        'width-thick': 'var(--al-border-width-thick)',
      }
    },
  },
  plugins: [],
}

