
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
      "spColorBackgroundSubtle": "var(--sp-color-background-subtle)",
      "spColorBackgroundLightest": "var(--sp-color-background-lightest)",
      "spColorBackgroundDarkest": "var(--sp-color-background-darkest)",
      "spColorTextDark": "var(--sp-color-text-dark)",
      "spColorTextMedium": "var(--sp-color-text-medium)",
      "spColorTextLightest": "var(--sp-color-text-lightest)",
      "spColorTextSubtle": "var(--sp-color-text-subtle)",
      "spColorTextStrong": "var(--sp-color-text-strong)",
      "spColorTextDisable": "var(--sp-color-text-disable)",
      "spColorTextAccentStrong": "var(--sp-color-text-accent-strong)",
      "spColorTextBrandExtreme": "var(--sp-color-text-brand-extreme)",
      "spColorTextBrandStrong": "var(--sp-color-text-brand-strong)",
      "spColorTextBrandMedium": "var(--sp-color-text-brand-medium)",
      "spColorTextFeedbackSuccess": "var(--sp-color-text-feedback-success)",
      "spColorTextFeedbackWarning": "var(--sp-color-text-feedback-warning)",
      "spColorTextFeedbackCritical": "var(--sp-color-text-feedback-critical)",
      "spColorTextFeedbackInformative": "var(--sp-color-text-feedback-informative)",
      "spColorSurfaceFeedbackSuccessStrong": "var(--sp-color-surface-feedback-success-strong)",
      "spColorSurfaceFeedbackSuccessSubtle": "var(--sp-color-surface-feedback-success-subtle)",
      "spColorSurfaceFeedbackCriticalStrong": "var(--sp-color-surface-feedback-critical-strong)",
      "spColorSurfaceFeedbackCriticalSubtle": "var(--sp-color-surface-feedback-critical-subtle)",
      "spColorSurfaceFeedbackWarningStrong": "var(--sp-color-surface-feedback-warning-strong)",
      "spColorSurfaceFeedbackWarningSubtle": "var(--sp-color-surface-feedback-warning-subtle)",
      "spColorSurfaceFeedbackInformativeStrong": "var(--sp-color-surface-feedback-informative-strong)",
      "spColorSurfaceFeedbackInformativeSubtle": "var(--sp-color-surface-feedback-informative-subtle)",
      "spColorSurfaceBrandStrong": "var(--sp-color-surface-brand-strong)",
      "spColorSurfaceBrandMedium": "var(--sp-color-surface-brand-medium)",
      "spColorSurfaceBrandSubtle": "var(--sp-color-surface-brand-subtle)",
      "spColorSurfaceBrandExtreme": "var(--sp-color-surface-brand-extreme)",
      "spColorSurfaceAccentStrong": "var(--sp-color-surface-accent-strong)",
      "spColorSurfaceAccentMedium": "var(--sp-color-surface-accent-medium)",
      "spColorSurfaceAccentExtreme": "var(--sp-color-surface-accent-extreme)",
      "spColorSurfaceAccentSubtle": "var(--sp-color-surface-accent-subtle)",
      "spColorSurfaceOpacitySubtle": "var(--sp-color-surface-opacity-subtle)",
      "spColorSurfaceOpacityHover": "var(--sp-color-surface-opacity-hover)",
      "spColorSurfaceSubtle": "var(--sp-color-surface-subtle)",
      "spColorSurfaceLightest": "var(--sp-color-surface-lightest)",
      "spColorSurfaceDisableInverse": "var(--sp-color-surface-disable-inverse)",
      "spColorSurfaceDisable": "var(--sp-color-surface-disable)",
      "spColorSurfaceMedium": "var(--sp-color-surface-medium)",
      "spColorSurfaceDark": "var(--sp-color-surface-dark)",
      "spColorBorderFeedbackSuccess": "var(--sp-color-border-feedback-success)",
      "spColorBorderFeedbackCritical": "var(--sp-color-border-feedback-critical)",
      "spColorBorderBrandStrong": "var(--sp-color-border-brand-strong)",
      "spColorBorderBrandMedium": "var(--sp-color-border-brand-medium)",
      "spColorBorderAccentMedium": "var(--sp-color-border-accent-medium)",
      "spColorBorderAccentExtreme": "var(--sp-color-border-accent-extreme)",
      "spColorBorderDark": "var(--sp-color-border-dark)",
      "spColorBorderMedium": "var(--sp-color-border-medium)",
      "spColorBorderDisable": "var(--sp-color-border-disable)",
      "spColorBorderSubtle": "var(--sp-color-border-subtle)",
      "spColorBorderLight": "var(--sp-color-border-light)",
      "spColorBorderLightest": "var(--sp-color-border-lightest)",
      "spColorBorderStrong": "var(--sp-color-border-strong)",
      "spColorIconDarkest": "var(--sp-color-icon-darkest)",
      "spColorIconDark": "var(--sp-color-icon-dark)",
      "spColorIconStrong": "var(--sp-color-icon-strong)",
      "spColorIconDisable": "var(--sp-color-icon-disable)",
      "spColorIconMedium": "var(--sp-color-icon-medium)",
      "spColorIconLightest": "var(--sp-color-icon-lightest)",
      "spColorIconDisableInverse": "var(--sp-color-icon-disable-inverse)",
      "spColorIconAccentStrong": "var(--sp-color-icon-accent-strong)",
      "spColorIconAccentMedium": "var(--sp-color-icon-accent-medium)",
      "spColorIconBrandStrong": "var(--sp-color-icon-brand-strong)",
      "spColorIconBrandSubtle": "var(--sp-color-icon-brand-subtle)",
      "spColorIconBrandExtreme": "var(--sp-color-icon-brand-extreme)",
      "spColorIconBrandMedium": "var(--sp-color-icon-brand-medium)",
      "spColorIconFeedbackSuccess": "var(--sp-color-icon-feedback-success)",
      "spColorIconFeedbackWarning": "var(--sp-color-icon-feedback-warning)",
      "spColorIconFeedbackCritical": "var(--sp-color-icon-feedback-critical)",
      "spColorIconFeedbackInformative": "var(--sp-color-icon-feedback-informative)",
      "spColorIconSubtle": "var(--sp-color-icon-subtle)"
},
      fontFamily: {
      "alFontFamilyPrimary": "var(--al-font-family-primary)",
      "alFontFamilySecondary": "var(--al-font-family-secondary)"
},
      fontSize: {
      "alFontSizeSm": "var(--al-font-size-sm)",
      "alFontSizeMd": "var(--al-font-size-md)",
      "alFontSizeXl": "var(--al-font-size-xl)",
      "alFontSizeLg": "var(--al-font-size-lg)",
      "alFontSize3xl": "var(--al-font-size-3xl)",
      "alFontSize2xl": "var(--al-font-size-2xl)",
      "alFontSize5xl": "var(--al-font-size-5xl)",
      "alFontSize4xl": "var(--al-font-size-4xl)",
      "alFontSize6xl": "var(--al-font-size-6xl)",
      "alFontSize7xl": "var(--al-font-size-7xl)",
      "alFontSizeDisplay": "var(--al-font-size-display)",
      "alFontSizeGiant": "var(--al-font-size-giant)",
      "alFontSize8xl": "var(--al-font-size-8xl)",
      "alFontSizeXs": "var(--al-font-size-xs)"
},
      fontWeight: {
      "alFontWeightLight": "var(--al-font-weight-light)",
      "alFontWeightRegular": "var(--al-font-weight-regular)",
      "alFontWeightBold": "var(--al-font-weight-bold)"
},
      letterSpacing: {
      "alFontLetterSpacingBase": "var(--al-font-letter-spacing-base)",
      "alFontLetterSpacingHalf": "var(--al-font-letter-spacing-half)",
      "alFontLetterSpacingLong": "var(--al-font-letter-spacing-long)",
      "alFontLetterSpacingShort": "var(--al-font-letter-spacing-short)"
},
      lineHeight: {
      "alFontLineHeightBase": "var(--al-font-line-height-base)",
      "alFontLineHeightNear": "var(--al-font-line-height-near)",
      "alFontLineHeightShort": "var(--al-font-line-height-short)",
      "alFontLineHeightHalf": "var(--al-font-line-height-half)",
      "alFontLineHeightLong": "var(--al-font-line-height-long)"
},
      spacing: {
      "alSpaceSm": "var(--al-space-sm)",
      "alSpaceMd": "var(--al-space-md)",
      "alSpaceLg": "var(--al-space-lg)",
      "alSpaceXl": "var(--al-space-xl)",
      "alSpace2xl": "var(--al-space-2xl)",
      "alSpace3xl": "var(--al-space-3xl)",
      "alSpace4xl": "var(--al-space-4xl)",
      "alSpace5xl": "var(--al-space-5xl)",
      "alSpace6xl": "var(--al-space-6xl)",
      "alSpace7xl": "var(--al-space-7xl)",
      "alSpace8xl": "var(--al-space-8xl)"
},
      borderRadius: {
      "alBorderRadiusSquare": "var(--al-border-radius-square)",
      "alBorderRadiusSm": "var(--al-border-radius-sm)",
      "alBorderRadiusMd": "var(--al-border-radius-md)",
      "alBorderRadiusLg": "var(--al-border-radius-lg)",
      "alBorderRadiusXl": "var(--al-border-radius-xl)",
      "alBorderRadiusPill": "var(--al-border-radius-pill)",
      "alBorderRadiusCircle": "var(--al-border-radius-circle)"
},
      borderWidth: {
      "alBorderWidthNone": "var(--al-border-width-none)",
      "alBorderWidthThin": "var(--al-border-width-thin)",
      "alBorderWidthRegular": "var(--al-border-width-regular)",
      "alBorderWidthThick": "var(--al-border-width-thick)"
},
      borderStyle: {
      "alBorderStyleNone": "var(--al-border-style-none)",
      "alBorderStyleSolid": "var(--al-border-style-solid)",
      "alBorderStyleDash": "var(--al-border-style-dash)"
}
    }
  }
}
